# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: deploy

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: dev

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Show dotnet bin path
      run: echo "${{ env.DOTNET_INSTALL_DIR }}"
    - name: Restore dependencies
      run: dotnet restore
    - name: Update database
      run: |
        dotnet new tool-manifest
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -c DataContext -p MyProj -s MyProjFactory
    - name: Build
      run: dotnet publish --no-restore
    - name: Restart service
      run: echo ${{ secrets.SUDOPASSWORD }} | sudo -S systemctl restart battari-api-dev
