# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: production

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: production

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Show dotnet bin path
      run: echo "${{ env.DOTNET_INSTALL_DIR }}"
    - name: Restore dependencies
      run: dotnet restore
    - name: download appsettings.json
      run: curl ${{ secrets.APPSETTINGS_URL_PROD }} -o appsettings.json
    - name: Update database
      run: |
        export PATH="$PATH:/home/runner/.dotnet/tools"
        dotnet new tool-manifest
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update
    - name: Build
      run: dotnet publish --no-restore
    - name: Restart service
      run: echo ${{ secrets.SUDOPASSWORD }} | sudo -S systemctl restart battari-api-prod
